# Revenue Analysis
# Assume the following monthly subscription prices, calculate the total revenue 
# generated by both 
# platforms (LioCinema and Jotstar) for the analysis period (January 
# to November 2024).  
# LioCinema basic 69 / premium 129
# Jotstar VIP 159 / Premium 359

# The calculation should consider: 
# ❖ Subscribers count under each plan. 
# ❖ Active duration of subscribers on their respective plans. 
# ❖ Upgrades and downgrades during the period, ensuring revenue reflects the 
# time spent under each plan. 


SELECT 'LioCinema' AS platform,
       subscription_plan, 
       COUNT(user_id) AS subscriber_count,
       CASE 
           WHEN subscription_plan = 'Basic' THEN 69
           WHEN subscription_plan = 'Premium' THEN 129
       END AS price_per_month,
       COUNT(user_id) * CASE 
           WHEN subscription_plan = 'Basic' THEN 69
           WHEN subscription_plan = 'Premium' THEN 129
       END AS total_revenue
FROM liocinema_db.subscribers
GROUP BY subscription_plan
UNION ALL
SELECT 'Jotstar' AS platform,
       subscription_plan, 
       COUNT(user_id) AS subscriber_count,
       CASE 
           WHEN subscription_plan = 'VIP' THEN 159
           WHEN subscription_plan = 'Premium' THEN 359
       END AS price_per_month,
       COUNT(user_id) * CASE 
           WHEN subscription_plan = 'VIP' THEN 159
           WHEN subscription_plan = 'Premium' THEN 359
       END AS total_revenue
FROM jotstar_db.subscribers
GROUP BY subscription_plan;
